name: Run Zizmor

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
      - ".github/**"

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-slim
    timeout-minutes: 45
    permissions:
      contents: read # needed to checkout the repo on private repos (no-op on public)
      security-events: write # needed for SARIF uploads
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # ratchet:astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: false
          version: "0.11.25"

      - name: Install zizmor from uv.lock
        run: uv sync --frozen --no-install-project --only-group zizmor

      - name: Run zizmor
        run: uv run --no-sync zizmor --format=sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@ba454b8ab46733eb6145342877cd148270bb77ab # ratchet:github/codeql-action/upload-sarif@codeql-bundle-v2.23.5
        with:
          sarif_file: results.sarif
          category: zizmor
